apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: order-service=536697223481.dkr.ecr.us-east-1.amazonaws.com/order-service
    argocd-image-updater.argoproj.io/order-service.update-strategy: latest
    argocd-image-updater.argoproj.io/order-service.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/techgirlie723/k8s-manifests.git
    targetRevision: HEAD
    path: order-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
